---
title: "iterations and listcols"
output: html_document
date: "2023-11-03"
---

### Lists

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "wendy")

tibble(
  num = vec_numeric,
  char = vec_char
)

```


Different stuff with different lengths
```{r}
l = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow = 5, ncol = 2),
    summary = summary(rnorm(100))
  )
```

Accessing lists
```{r}
l$vec_char

l[[2]]

l[["summary"]]
```


### Loops
```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```

mean and sd function
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }

  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```


```{r}
mean_and_sd(list_norm_samples$a)

mean_and_sd(list_norm_samples$b)

mean_and_sd(list_norm_samples$c)

mean_and_sd(list_norm_samples$d)
```

write as for loop
```{r}
output_mean_sd = vector("list", length = 4)
output_median = vector("list", length = 4)

for (i in 1:4) {
  
  output_mean_sd[[i]] = mean_and_sd(list_norm_samples[[i]])
  output_median[[i]] = median(list_norm_samples[[i]])
  
}
```

### use map function
```{r}
output_mean_sd = map(list_norm_samples, mean_and_sd)
output_summary = map(list_norm_samples, summary)
```




